<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CatalogSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::connection('tenant')->table('catalogs')->insert([
            ['cat_name' => 'Viviendas', 'parent_id' => NULL, 'cat_description' => NULL, 'cat_acronym' => 'VV', 'cat_keyword' => NULL, 'status_id' => 1],
            ['cat_name' => 'Tipo de viviendas', 'parent_id' => NULL, 'cat_description' => NULL, 'cat_acronym' => 'TV', 'cat_keyword' => NULL, 'status_id' => 1],
            ['cat_name' => 'Redes sociales', 'parent_id' => NULL, 'cat_description' => NULL, 'cat_acronym' => 'RS', 'cat_keyword' => NULL, 'status_id' => 1],
            ['cat_name' => 'Servicios basicos', 'parent_id' => NULL, 'cat_description' => NULL, 'cat_acronym' => 'SB', 'cat_keyword' => NULL, 'status_id' => 1],
            ['cat_name' => 'Generos', 'parent_id' => NULL, 'cat_description' => NULL, 'cat_acronym' => 'G', 'cat_keyword' => NULL, 'status_id' => 1],
            ['cat_name' => 'Estado Civil', 'parent_id' => NULL, 'cat_description' => NULL, 'cat_acronym' => 'SM', 'cat_keyword' => NULL, 'status_id' => 1],
            ['cat_name' => 'Religion', 'parent_id' => NULL, 'cat_description' => NULL, 'cat_acronym' => 'TR', 'cat_keyword' => NULL, 'status_id' => 1],
            ['cat_name' => 'Ciudad', 'parent_id' => NULL, 'cat_description' => NULL, 'cat_acronym' => 'C', 'cat_keyword' => NULL, 'status_id' => 1],
            ['cat_name' => 'Sector', 'parent_id' => NULL, 'cat_description' => NULL, 'cat_acronym' => 'S', 'cat_keyword' => NULL, 'status_id' => 1],
            ['cat_name' => 'Etnia', 'parent_id' => NULL, 'cat_description' => NULL, 'cat_acronym' => 'ET', 'cat_keyword' => NULL, 'status_id' => 1],
            ['cat_name' => 'Tipo de Identificacion', 'parent_id' => NULL, 'cat_description' => NULL, 'cat_acronym' => 'TI', 'cat_keyword' => NULL, 'status_id' => 1],
            ['cat_name' => 'Modalidad', 'parent_id' => NULL, 'cat_description' => NULL, 'cat_acronym' => 'M', 'cat_keyword' => NULL, 'status_id' => 1],
            ['cat_name' => 'Jornada', 'parent_id' => NULL, 'cat_description' => NULL, 'cat_acronym' => 'J', 'cat_keyword' => NULL, 'status_id' => 1],
            ['cat_name' => 'Parentesco', 'parent_id' => NULL, 'cat_description' => NULL, 'cat_acronym' => 'P', 'cat_keyword' => NULL, 'status_id' => 1],
            ['cat_name' => 'Idiomas', 'parent_id' => NULL, 'cat_description' => NULL, 'cat_acronym' => 'I', 'cat_keyword' => NULL, 'status_id' => 1],
            ['cat_name' => 'Nacionalidad', 'parent_id' => NULL, 'cat_description' => NULL, 'cat_acronym' => 'NA', 'cat_keyword' => NULL, 'status_id' => 1],

            ['cat_name' => 'Casa', 'parent_id' => 1, 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'vivienda-casa', 'status_id' => 1],
            ['cat_name' => 'Apartamento', 'parent_id' => 1, 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'vivienda-apartamento', 'status_id' => 1],
            ['cat_name' => 'Edificio', 'parent_id' => 1, 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'vivienda-edificio', 'status_id' => 1],
            ['cat_name' => 'Mansion', 'parent_id' => 1, 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'vivienda-mansion', 'status_id' => 1],

            ['cat_name' => 'Madera', 'parent_id' => 2, 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'tipo-vivienda-madera', 'status_id' => 1],
            ['cat_name' => 'Ladrillo', 'parent_id' => 2, 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'tipo-vivienda-ladrillo', 'status_id' => 1],
            ['cat_name' => 'Hormigon', 'parent_id' => 2, 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'tipo-vivienda-hormigon', 'status_id' => 1],
            ['cat_name' => 'Acero', 'parent_id' => 2, 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'tipo-vivienda-acero', 'status_id' => 1],
            ['cat_name' => 'Mixtas', 'parent_id' => 2, 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'tipo-vivienda-mixtas', 'status_id' => 1],

            ['cat_name' => 'Facebook', 'parent_id' => 3, 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'red-social-facebook', 'status_id' => 1],
            ['cat_name' => 'WhatsApp', 'parent_id' => 3, 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'red-social-whatsapp', 'status_id' => 1],
            ['cat_name' => 'Instagram', 'parent_id' => 3, 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'red-social-instagram', 'status_id' => 1],
            ['cat_name' => 'Twitter', 'parent_id' => 3, 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'red-social-twitter', 'status_id' => 1],
            ['cat_name' => 'LinkedIn', 'parent_id' => 3, 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'red-social-linkedin', 'status_id' => 1],

            ['cat_name' => 'Agua', 'parent_id' => 4, 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'servicio-agua', 'status_id' => 1],
            ['cat_name' => 'Luz', 'parent_id' => 4, 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'servicio-luz', 'status_id' => 1],
            ['cat_name' => 'Telefono', 'parent_id' => 4, 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'servicio-telefono', 'status_id' => 1],

            ['cat_name' => 'Masculino', 'parent_id' => 5, 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => NULL, 'status_id' => 1],
            ['cat_name' => 'Femenino', 'parent_id' => 5, 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => NULL, 'status_id' => 1],

            ['cat_name' => 'Casado/a', 'parent_id' => 6, 'cat_description' => 'Persona en matrimonio', 'cat_acronym' => NULL, 'cat_keyword' => 'casado', 'status_id' => 1],
            ['cat_name' => 'Soltero/a', 'parent_id' => 6, 'cat_description' => 'Persona soltera', 'cat_acronym' => NULL, 'cat_keyword' => 'soltero', 'status_id' => 1],
            ['cat_name' => 'Viudo/a', 'parent_id' => 6, 'cat_description' => 'Persona viuda', 'cat_acronym' => NULL, 'cat_keyword' => 'viudo', 'status_id' => 1],
            ['cat_name' => 'Divorciado/a', 'parent_id' => 6, 'cat_description' => 'Persona divorciada', 'cat_acronym' => NULL, 'cat_keyword' => 'divorciado', 'status_id' => 1],

            ['cat_name' => 'Cristiano', 'parent_id' => 7, 'cat_description' => 'Cristanismo', 'cat_acronym' => NULL, 'cat_keyword' => 'cristiano', 'status_id' => 1],
            ['cat_name' => 'Catolico', 'parent_id' => 7, 'cat_description' => 'Catolicismo', 'cat_acronym' => NULL, 'cat_keyword' => 'catolico', 'status_id' => 1],
            ['cat_name' => 'Islam', 'parent_id' => 7, 'cat_description' => 'Islam', 'cat_acronym' => NULL, 'cat_keyword' => 'islam', 'status_id' => 1],
            ['cat_name' => 'Hinduismo', 'parent_id' => 7, 'cat_description' => 'Hinduismo', 'cat_acronym' => NULL, 'cat_keyword' => 'hinduismo', 'status_id' => 1],
            ['cat_name' => 'Budismo', 'parent_id' => 7, 'cat_description' => 'Budismo', 'cat_acronym' => NULL, 'cat_keyword' => 'budismo', 'status_id' => 1],
            ['cat_name' => 'Judaismo', 'parent_id' => 7, 'cat_description' => 'Judaismo', 'cat_acronym' => NULL, 'cat_keyword' => 'judaismo', 'status_id' => 1],
            ['cat_name' => 'Agnostico', 'parent_id' => 7, 'cat_description' => 'Agnostico', 'cat_acronym' => NULL, 'cat_keyword' => 'agnostico', 'status_id' => 1],
            ['cat_name' => 'Ateo', 'parent_id' => 7, 'cat_description' => 'Ateo', 'cat_acronym' => NULL, 'cat_keyword' => 'ateo', 'status_id' => 1],
            ['cat_name' => 'Otros', 'parent_id' => 7, 'cat_description' => 'Otras religiones', 'cat_acronym' => NULL, 'cat_keyword' => 'religion-otros', 'status_id' => 1],
            ['cat_name' => 'Ninguno', 'parent_id' => 7, 'cat_description' => 'Ninguno', 'cat_acronym' => NULL, 'cat_keyword' => 'religion-ninguno', 'status_id' => 1],

            ['cat_name' => 'Guayaquil', 'parent_id' => 8, 'cat_description' => NULL, 'cat_acronym' => 'Gye', 'cat_keyword' => 'ciudad-guayaquil', 'status_id' => 1],
            ['cat_name' => 'Samborondon', 'parent_id' => 8, 'cat_description' => NULL, 'cat_acronym' => 'Samb', 'cat_keyword' => 'ciudad-samborondon', 'status_id' => 1],
            ['cat_name' => 'Cuenca', 'parent_id' => 8, 'cat_description' => NULL, 'cat_acronym' => 'Cuen', 'cat_keyword' => 'ciudad-cuenca', 'status_id' => 1],
            ['cat_name' => 'Quito', 'parent_id' => 8, 'cat_description' => NULL, 'cat_acronym' => 'DMQ', 'cat_keyword' => 'ciudad-quito', 'status_id' => 1],
            ['cat_name' => 'Babahoyo', 'parent_id' => 8, 'cat_description' => NULL, 'cat_acronym' => 'Bbhy', 'cat_keyword' => 'ciudad-babahoyo', 'status_id' => 1],

            ['cat_name' => 'Ximena', 'parent_id' => 9, 'cat_description' => NULL, 'cat_acronym' => NULL,  'cat_keyword' => 'sector-ximena', 'status_id' => 1],
            ['cat_name' => 'Los Esteros', 'parent_id' => 9, 'cat_description' => NULL, 'cat_acronym' => NULL,  'cat_keyword' => 'sector-estereos', 'status_id' => 1,],
            ['cat_name' => 'Febres Cordero', 'parent_id' => 9, 'cat_description' => NULL, 'cat_acronym' => NULL,  'cat_keyword' => 'sector-febres-cordero', 'status_id' => 1],
            ['cat_name' => 'Las Peñas', 'parent_id' => 9, 'cat_description' => NULL, 'cat_acronym' => NULL,  'cat_keyword' => 'sector-las-peñas', 'status_id' => 1],
            ['cat_name' => 'Centenario', 'parent_id' => 9, 'cat_description' => NULL, 'cat_acronym' => NULL,  'cat_keyword' => 'sector-centenario', 'status_id' => 1],
            ['cat_name' => 'Urdesa', 'parent_id' => 9, 'cat_description' => NULL, 'cat_acronym' => NULL,  'cat_keyword' => 'sector-urdesa', 'status_id' => 1],

            ['cat_name' => 'Mestizo', 'parent_id' => 10, 'cat_description' => 'Mestizo', 'cat_acronym' => NULL, 'cat_keyword' => 'mestizo', 'status_id' => 1],
            ['cat_name' => 'Montubio', 'parent_id' => 10, 'cat_description' => 'Montubio', 'cat_acronym' => NULL, 'cat_keyword' => 'monturbio', 'status_id' => 1],
            ['cat_name' => 'Afroecuatoriano', 'parent_id' => 10, 'cat_description' => 'Afroecuatoriano', 'cat_acronym' => NULL, 'cat_keyword' => 'afroecuatoriano', 'status_id' => 1],
            ['cat_name' => 'Indigena', 'parent_id' => 10, 'cat_description' => 'Indigena', 'cat_acronym' => NULL, 'cat_keyword' => 'indigena', 'status_id' => 1],
            ['cat_name' => 'Blanco', 'parent_id' => 10, 'cat_description' => 'Blanco', 'cat_acronym' => NULL, 'cat_keyword' => 'blanco', 'status_id' => 1],
            ['cat_name' => 'Asiatico', 'parent_id' => 10, 'cat_description' => 'Asiatico', 'cat_acronym' => NULL, 'cat_keyword' => 'asiatico', 'status_id' => 1],

            ['cat_name' => 'Cédula', 'parent_id' => 11, 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'cedula', 'status_id' => 1],
            ['cat_name' => 'RUC', 'parent_id' => 11, 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'ruc', 'status_id' => 1],
            ['cat_name' => 'DNI', 'parent_id' => 11, 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'dni', 'status_id' => 1],
            ['cat_name' => 'Pasaporte', 'parent_id' => 11, 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'pasaporte', 'status_id' => 1],

            ['cat_name' => 'Presencial', 'parent_id' => 12, 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'jornada-presencial', 'status_id' => 1],

            ['cat_name' => 'Matutina', 'parent_id' => 13, 'cat_description' => 'En la mañana', 'cat_acronym' => NULL, 'cat_keyword' => 'seccion-matutina', 'status_id' => 1],
            ['cat_name' => 'Vespertina', 'parent_id' => 13, 'cat_description' => 'En la tarde', 'cat_acronym' => NULL, 'cat_keyword' => 'seccion-vespertina', 'status_id' => 1],
            ['cat_name' => 'Nocturna', 'parent_id' => 13, 'cat_description' => 'En la noche', 'cat_acronym' => NULL, 'cat_keyword' => 'seccion-nocturna', 'status_id' => 1],

            ['cat_name' => 'Mama', 'parent_id' => 14, 'cat_description' => 'Parentesco Mama', 'cat_acronym' => NULL, 'cat_keyword' => 'mama', 'status_id' => 1],
            ['cat_name' => 'Papa', 'parent_id' => 14, 'cat_description' => 'Parentesco Papa', 'cat_acronym' => NULL, 'cat_keyword' => 'papa', 'status_id' => 1],
            ['cat_name' => 'Hermano/a', 'parent_id' => 14, 'cat_description' => 'Parentesco Hermano/a', 'cat_acronym' => NULL, 'cat_keyword' => 'hermano',  'status_id' => 1],
            ['cat_name' => 'Tio/a', 'parent_id' => 14, 'cat_description' => 'Tio/a', 'cat_acronym' => NULL, 'cat_keyword' => 'tio', 'status_id' => 1],
            ['cat_name' => 'Abuelo/a', 'parent_id' => 14, 'cat_description' => 'Abuelo/a', 'cat_acronym' => NULL, 'cat_keyword' => 'abuelo', 'status_id' => 1],
            ['cat_name' => 'Primo/a', 'parent_id' => 14, 'cat_description' => 'Primo/a', 'cat_acronym' => NULL, 'cat_keyword' => 'primo', 'status_id' => 1],
            ['cat_name' => 'Esposo/a', 'parent_id' => 14, 'cat_description' => 'Esposo/a', 'cat_acronym' => NULL, 'cat_keyword' => 'esposo', 'status_id' => 1],
            ['cat_name' => 'Amigo/a', 'parent_id' => 14, 'cat_description' => 'Amigo/a', 'cat_acronym' => NULL, 'cat_keyword' => 'amigo', 'status_id' => 1],
            ['cat_name' => 'Otro/a', 'parent_id' => 14, 'cat_description' => 'Otro/a', 'cat_acronym' => NULL, 'cat_keyword' => 'otro', 'status_id' => 1],

            ['cat_name' => 'Español', 'parent_id' => 15, 'cat_description' => 'Habla idioma español', 'cat_acronym' => NULL, 'cat_keyword' => 'espaniol', 'status_id' => 1],
            ['cat_name' => 'Inglés', 'parent_id' => 15, 'cat_description' => 'Habla idioma inglés', 'cat_acronym' => NULL, 'cat_keyword' => 'ingles', 'status_id' => 1],
            ['cat_name' => 'Francés', 'parent_id' => 15, 'cat_description' => 'Habla idioma francés', 'cat_acronym' => NULL, 'cat_keyword' => 'frances', 'status_id' => 1],
            ['cat_name' => 'Chino', 'parent_id' => 15, 'cat_description' => 'Habla idioma chino mandarin', 'cat_acronym' => NULL, 'cat_keyword' => 'chino', 'status_id' => 1],

            ['cat_name' => 'Ecuatoriana', 'parent_id' => 16, 'cat_description' => 'Nacionalidad ecuatoriana', 'cat_acronym' => NULL, 'cat_keyword' => 'ecuatoriana', 'status_id' => 1],
            ['cat_name' => 'Venezolana', 'parent_id' => 16, 'cat_description' => 'Nacionalidad venezolana', 'cat_acronym' => NULL, 'cat_keyword' => 'venezolana', 'status_id' => 1],
            ['cat_name' => 'Colombiana', 'parent_id' => 16, 'cat_description' => 'Nacionalidad colombiana', 'cat_acronym' => NULL, 'cat_keyword' => 'colombiana', 'status_id' => 1],
            ['cat_name' => 'Boliviana', 'parent_id' => 16, 'cat_description' => 'Nacionalidad boliviana', 'cat_acronym' => NULL, 'cat_keyword' => 'boliviana', 'status_id' => 1],
            ['cat_name' => 'Mexicana', 'parent_id' => 16, 'cat_description' => 'Nacionalidad mexicana', 'cat_acronym' => NULL, 'cat_keyword' => 'mexicana', 'status_id' => 1],
            ['cat_name' => 'Española', 'parent_id' => 16, 'cat_description' => 'Nacionalidad española', 'cat_acronym' => NULL, 'cat_keyword' => 'espaniola', 'status_id' => 1],
            ['cat_name' => 'Noruega', 'parent_id' => 16, 'cat_description' => 'Nacionalidad noruega', 'cat_acronym' => NULL, 'cat_keyword' => 'noruega', 'status_id' => 1],

            /* Paises - Provincia - Canton */
            ['cat_name' => 'Paises', 'cat_description' => NULL, 'cat_acronym' => 'PS', 'cat_keyword' => 'paises', 'parent_id' => NULL, 'status_id' => 1],
            ['cat_name' => 'Ecuador', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'pais-ec', 'parent_id' => 95, 'status_id' => 1],
            ['cat_name' => 'Esmeraldas', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'provincia-ec-esmeralda', 'parent_id' => 96, 'status_id' => 1],
            ['cat_name' => 'Manabi', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'provincia-ec-manabi', 'parent_id' => 96, 'status_id' => 1],
            ['cat_name' => 'Los Rios', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'provincia-ec-los-rios', 'parent_id' => 96, 'status_id' => 1],
            ['cat_name' => 'Guayas', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'provincia-ec-guayas', 'parent_id' => 96, 'status_id' => 1],
            ['cat_name' => 'Santa Elena', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'provincia-ec-sta-elena', 'parent_id' => 96, 'status_id' => 1],
            ['cat_name' => 'Santo Domingo de los Tsachilas', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'provincia-ec-sto-domingo', 'parent_id' => 96, 'status_id' => 1],
            ['cat_name' => 'El Oro', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'provincia-ec-el-oro', 'parent_id' => 96, 'status_id' => 1],
            ['cat_name' => 'Carchi', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'provincia-ec-carchi', 'parent_id' => 96, 'status_id' => 1],
            ['cat_name' => 'Imbabura', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'provincia-ec-imbabura', 'parent_id' => 96, 'status_id' => 1],
            ['cat_name' => 'Pichincha', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'provincia-ec-pichincha', 'parent_id' => 96, 'status_id' => 1],
            ['cat_name' => 'Cotopaxi', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'provincia-ec-cotopaxi', 'parent_id' => 96, 'status_id' => 1],
            ['cat_name' => 'Tungurahua', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'provincia-ec-tungurahua', 'parent_id' => 96, 'status_id' => 1],
            ['cat_name' => 'Bolivar', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'provincia-ec-bolivar', 'parent_id' => 96, 'status_id' => 1],
            ['cat_name' => 'Chimborazo', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'provincia-ec-chimborazo', 'parent_id' => 96, 'status_id' => 1],
            ['cat_name' => 'Cañar', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'provincia-ec-canar', 'parent_id' => 96, 'status_id' => 1],
            ['cat_name' => 'Azuay', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'provincia-ec-azuay', 'parent_id' => 96, 'status_id' => 1],
            ['cat_name' => 'Loja', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'provincia-ec-loja', 'parent_id' => 96, 'status_id' => 1],
            ['cat_name' => 'Sucumbios', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'provincia-ec-sucumbios', 'parent_id' => 96, 'status_id' => 1],
            ['cat_name' => 'Napo', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'provincia-ec-napo', 'parent_id' => 96, 'status_id' => 1],
            ['cat_name' => 'Orellana', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'provincia-ec-orellana', 'parent_id' => 96, 'status_id' => 1],
            ['cat_name' => 'Pastaza', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'provincia-ec-pastaza', 'parent_id' => 96, 'status_id' => 1],
            ['cat_name' => 'Morona Santiago', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'provincia-ec-morona-santiago', 'parent_id' => 96, 'status_id' => 1],
            ['cat_name' => 'Zamora Chinchipe', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'provincia-ec-zamora-chinchipe', 'parent_id' => 96, 'status_id' => 1],
            ['cat_name' => 'Galapagos', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'provincia-ec-galapagos', 'parent_id' => 96, 'status_id' => 1],
            ['cat_name' => 'Esmeraldas', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-esmeraldas', 'parent_id' => 97, 'status_id' => 1],
            ['cat_name' => 'Atacames', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-atacames', 'parent_id' => 97, 'status_id' => 1],
            ['cat_name' => 'Valdez', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-valdez', 'parent_id' => 97, 'status_id' => 1],
            ['cat_name' => 'Muisne', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-muisne', 'parent_id' => 97, 'status_id' => 1],
            ['cat_name' => 'Rosa Zarate', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-rosa-zarate', 'parent_id' => 97, 'status_id' => 1],
            ['cat_name' => 'Rioverde', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-rioverde', 'parent_id' => 97, 'status_id' => 1],
            ['cat_name' => 'San Lorenzo', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-san-lorenzo', 'parent_id' => 97, 'status_id' => 1],
            ['cat_name' => 'Bolivar', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-bolivar-manabi', 'parent_id' => 98, 'status_id' => 1],
            ['cat_name' => 'Chone', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-chone', 'parent_id' => 98, 'status_id' => 1],
            ['cat_name' => 'El Carmen', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-el-carmen', 'parent_id' => 98, 'status_id' => 1],
            ['cat_name' => 'Flavio Alfaro', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-flavio-alfaro', 'parent_id' => 98, 'status_id' => 1],
            ['cat_name' => 'Jama', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-jama', 'parent_id' => 98, 'status_id' => 1],
            ['cat_name' => 'Jaramijo', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-jaramijo', 'parent_id' => 98, 'status_id' => 1],
            ['cat_name' => 'Jipijapa', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-jipijapa', 'parent_id' => 98, 'status_id' => 1],
            ['cat_name' => 'Junin', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-junin', 'parent_id' => 98, 'status_id' => 1],
            ['cat_name' => 'Manta', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-manta', 'parent_id' => 98, 'status_id' => 1],
            ['cat_name' => 'Montecristi', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-montecristi', 'parent_id' => 98, 'status_id' => 1],
            ['cat_name' => 'Olmedo', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-olmedo-manabi', 'parent_id' => 98, 'status_id' => 1],
            ['cat_name' => 'Pajan', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-pajan', 'parent_id' => 98, 'status_id' => 1],
            ['cat_name' => 'Pedernales', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-pedernales', 'parent_id' => 98, 'status_id' => 1],
            ['cat_name' => 'Pichincha', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-pichincha', 'parent_id' => 98, 'status_id' => 1],
            ['cat_name' => 'Portoviejo', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-portoviejo', 'parent_id' => 98, 'status_id' => 1],
            ['cat_name' => 'Puerto Lopez', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-puerto-lopez', 'parent_id' => 98, 'status_id' => 1],
            ['cat_name' => 'Rocafuerte', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-rocafuerte', 'parent_id' => 98, 'status_id' => 1],
            ['cat_name' => 'San Vicente', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-san-vicente', 'parent_id' => 98, 'status_id' => 1],
            ['cat_name' => 'Santa Ana', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-santa-ana', 'parent_id' => 98, 'status_id' => 1],
            ['cat_name' => 'Sucre', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-sucre', 'parent_id' => 98, 'status_id' => 1],
            ['cat_name' => 'Tosagua', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-tosagua', 'parent_id' => 98, 'status_id' => 1],
            ['cat_name' => 'Veinticuatro de Mayo', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-veinticuatro-mayo', 'parent_id' => 98, 'status_id' => 1],
            ['cat_name' => 'Baba', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-baba', 'parent_id' => 99, 'status_id' => 1],
            ['cat_name' => 'Babahoyo', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-babahoyo', 'parent_id' => 99, 'status_id' => 1],
            ['cat_name' => 'Buena Fe', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-buena-fe', 'parent_id' => 99, 'status_id' => 1],
            ['cat_name' => 'Mocache', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-mocache', 'parent_id' => 99, 'status_id' => 1],
            ['cat_name' => 'Montalvo', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-montalvo', 'parent_id' => 99, 'status_id' => 1],
            ['cat_name' => 'Palenque', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-palenque', 'parent_id' => 99, 'status_id' => 1],
            ['cat_name' => 'Puebloviejo', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-puebloviejo', 'parent_id' => 99, 'status_id' => 1],
            ['cat_name' => 'Quevedo', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-quevedo', 'parent_id' => 99, 'status_id' => 1],
            ['cat_name' => 'Quinsaloma', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-quinsaloma', 'parent_id' => 99, 'status_id' => 1],
            ['cat_name' => 'Urdaneta', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-urdaneta', 'parent_id' => 99, 'status_id' => 1],
            ['cat_name' => 'Valencia', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-valencia', 'parent_id' => 99, 'status_id' => 1],
            ['cat_name' => 'Ventanas', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-ventanas', 'parent_id' => 99, 'status_id' => 1],
            ['cat_name' => 'Vinces', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-vinces', 'parent_id' => 99, 'status_id' => 1],
            ['cat_name' => 'Guayaquil', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-guayaquil', 'parent_id' => 100, 'status_id' => 1],
            ['cat_name' => 'Alfredo Baquerizo Moreno', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-alfredo-baq-moreno', 'parent_id' => 100, 'status_id' => 1],
            ['cat_name' => 'Balao', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-balao', 'parent_id' => 100, 'status_id' => 1],
            ['cat_name' => 'Balzar', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-balzar', 'parent_id' => 100, 'status_id' => 1],
            ['cat_name' => 'Colimes', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-colimes', 'parent_id' => 100, 'status_id' => 1],
            ['cat_name' => 'Coronel Marcelino Maridueña', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-cnel-marcelino-mariduena', 'parent_id' => 100, 'status_id' => 1],
            ['cat_name' => 'Daule', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-daule', 'parent_id' => 100, 'status_id' => 1],
            ['cat_name' => 'Duran', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-duran', 'parent_id' => 100, 'status_id' => 1],
            ['cat_name' => 'El Empalme', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-el-empalme', 'parent_id' => 100, 'status_id' => 1],
            ['cat_name' => 'El Triunfo', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-el-triunfo', 'parent_id' => 100, 'status_id' => 1],
            ['cat_name' => 'General Antonio Elizalde', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-gral-antonio-elizalde', 'parent_id' => 100, 'status_id' => 1],
            ['cat_name' => 'Isidro Ayora', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-isidro-ayora', 'parent_id' => 100, 'status_id' => 1],
            ['cat_name' => 'Lomas de Sargentillo', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-lomas-sargentillo', 'parent_id' => 100, 'status_id' => 1],
            ['cat_name' => 'Milagro', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-milagro', 'parent_id' => 100, 'status_id' => 1],
            ['cat_name' => 'Naranjal', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-naranjal', 'parent_id' => 100, 'status_id' => 1],
            ['cat_name' => 'Naranjito', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-naranjito', 'parent_id' => 100, 'status_id' => 1],
            ['cat_name' => 'Nobol', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-nobol', 'parent_id' => 100, 'status_id' => 1],
            ['cat_name' => 'Palestina', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-palestina', 'parent_id' => 100, 'status_id' => 1],
            ['cat_name' => 'Pedro Carbo', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-pedro-carbo', 'parent_id' => 100, 'status_id' => 1],
            ['cat_name' => 'Playas', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-playas', 'parent_id' => 100, 'status_id' => 1],
            ['cat_name' => 'Salitre', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-salitre', 'parent_id' => 100, 'status_id' => 1],
            ['cat_name' => 'Samborondon', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-samborondon', 'parent_id' => 100, 'status_id' => 1],
            ['cat_name' => 'Santa Lucia', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-santa-lucia', 'parent_id' => 100, 'status_id' => 1],
            ['cat_name' => 'Simon Bolivar', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-simon-bolivar', 'parent_id' => 100, 'status_id' => 1],
            ['cat_name' => 'Yaguachi', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-yaguachi', 'parent_id' => 100, 'status_id' => 1],
            ['cat_name' => 'Santa Elena', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-santa-elena', 'parent_id' => 101, 'status_id' => 1],
            ['cat_name' => 'La Libertad', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-la-libertad', 'parent_id' => 101, 'status_id' => 1],
            ['cat_name' => 'Salinas', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-salinas', 'parent_id' => 101, 'status_id' => 1],
            ['cat_name' => 'La Concordia', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-la-concordia', 'parent_id' => 102, 'status_id' => 1],
            ['cat_name' => 'Santo Domingo', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-sto-domingo', 'parent_id' => 102, 'status_id' => 1],
            ['cat_name' => 'Arenillas', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-arenillas', 'parent_id' => 103, 'status_id' => 1],
            ['cat_name' => 'Atahualpa', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-atahualpa', 'parent_id' => 103, 'status_id' => 1],
            ['cat_name' => 'Balsas', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-balsas', 'parent_id' => 103, 'status_id' => 1],
            ['cat_name' => 'Chilla', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-chilla', 'parent_id' => 103, 'status_id' => 1],
            ['cat_name' => 'El Guabo', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-el-guabo', 'parent_id' => 103, 'status_id' => 1],
            ['cat_name' => 'Huaquillas', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-huaquillas', 'parent_id' => 103, 'status_id' => 1],
            ['cat_name' => 'Las Lajas', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-las-lajas', 'parent_id' => 103, 'status_id' => 1],
            ['cat_name' => 'Machala', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-machala', 'parent_id' => 103, 'status_id' => 1],
            ['cat_name' => 'Marcabeli', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-marcabeli', 'parent_id' => 103, 'status_id' => 1],
            ['cat_name' => 'Pasaje', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-pasaje', 'parent_id' => 103, 'status_id' => 1],
            ['cat_name' => 'Piñas', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-pinas', 'parent_id' => 103, 'status_id' => 1],
            ['cat_name' => 'Portovelo', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-portovelo', 'parent_id' => 103, 'status_id' => 1],
            ['cat_name' => 'Santa Rosa', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-santa-rosa', 'parent_id' => 103, 'status_id' => 1],
            ['cat_name' => 'Zaruma', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-zaruma', 'parent_id' => 103, 'status_id' => 1],
            ['cat_name' => 'Bolivar', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-bolivar-carchi', 'parent_id' => 104, 'status_id' => 1],
            ['cat_name' => 'Espejo', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-espejo', 'parent_id' => 104, 'status_id' => 1],
            ['cat_name' => 'Mira', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-mira', 'parent_id' => 104, 'status_id' => 1],
            ['cat_name' => 'Montufar', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-montufar', 'parent_id' => 104, 'status_id' => 1],
            ['cat_name' => 'San Pedro de Huaca', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-san-pedro-huaca', 'parent_id' => 104, 'status_id' => 1],
            ['cat_name' => 'Tulcan', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-tulcan', 'parent_id' => 104, 'status_id' => 1],
            ['cat_name' => 'Antonio Ante', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-antonio-ante', 'parent_id' => 105, 'status_id' => 1],
            ['cat_name' => 'Cotacachi', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-cotacachi', 'parent_id' => 105, 'status_id' => 1],
            ['cat_name' => 'Ibarra', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-ibarra', 'parent_id' => 105, 'status_id' => 1],
            ['cat_name' => 'Otavalo', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-otavalo', 'parent_id' => 105, 'status_id' => 1],
            ['cat_name' => 'Pimampiro', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-pimampiro', 'parent_id' => 105, 'status_id' => 1],
            ['cat_name' => 'Urcuqui', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-urcuqui', 'parent_id' => 105, 'status_id' => 1],
            ['cat_name' => 'Cayambe', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-cayambe', 'parent_id' => 106, 'status_id' => 1],
            ['cat_name' => 'Mejia', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-mejia', 'parent_id' => 106, 'status_id' => 1],
            ['cat_name' => 'Pedro Moncayo', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-pedro-mocayo', 'parent_id' => 106, 'status_id' => 1],
            ['cat_name' => 'Pedro Vicente Maldonado', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-pedro-vicente-maldonado', 'parent_id' => 106, 'status_id' => 1],
            ['cat_name' => 'Puerto Quito', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-puerto-quito', 'parent_id' => 106, 'status_id' => 1],
            ['cat_name' => 'Rumiñahui', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-ruminahui', 'parent_id' => 106, 'status_id' => 1],
            ['cat_name' => 'San Miguel de los Bancos', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-san-miguel-bancos', 'parent_id' => 106, 'status_id' => 1],
            ['cat_name' => 'La Mana', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-la-mana', 'parent_id' => 107, 'status_id' => 1],
            ['cat_name' => 'Latacunga', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-latacunga', 'parent_id' => 107, 'status_id' => 1],
            ['cat_name' => 'Pangua', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-pangua', 'parent_id' => 107, 'status_id' => 1],
            ['cat_name' => 'Pujili', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-pujili', 'parent_id' => 107, 'status_id' => 1],
            ['cat_name' => 'Salcedo', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-salcedo', 'parent_id' => 107, 'status_id' => 1],
            ['cat_name' => 'Saquisili', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-saquisili', 'parent_id' => 107, 'status_id' => 1],
            ['cat_name' => 'Sigchos', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-sigchos', 'parent_id' => 107, 'status_id' => 1],
            ['cat_name' => 'Ambato', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-ambato', 'parent_id' => 108, 'status_id' => 1],
            ['cat_name' => 'Baños de Agua Santa', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-bano-agua-santa', 'parent_id' => 108, 'status_id' => 1],
            ['cat_name' => 'Cevallos', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-cevallos', 'parent_id' => 108, 'status_id' => 1],
            ['cat_name' => 'Mocha', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-mocha', 'parent_id' => 108, 'status_id' => 1],
            ['cat_name' => 'Patate', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-patate', 'parent_id' => 108, 'status_id' => 1],
            ['cat_name' => 'Pelileo', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-pelileo', 'parent_id' => 108, 'status_id' => 1],
            ['cat_name' => 'Pillaro', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-pillaro', 'parent_id' => 108, 'status_id' => 1],
            ['cat_name' => 'Quero', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-quero', 'parent_id' => 108, 'status_id' => 1],
            ['cat_name' => 'Tisaleo', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-tisaleo', 'parent_id' => 108, 'status_id' => 1],
            ['cat_name' => 'Caluma', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-caluma', 'parent_id' => 109, 'status_id' => 1],
            ['cat_name' => 'Chillanes', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-chillanes', 'parent_id' => 109, 'status_id' => 1],
            ['cat_name' => 'Chimbo', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-chimbo', 'parent_id' => 109, 'status_id' => 1],
            ['cat_name' => 'Echeandia', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-echeandia', 'parent_id' => 109, 'status_id' => 1],
            ['cat_name' => 'Guaranda', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-guaranda', 'parent_id' => 109, 'status_id' => 1],
            ['cat_name' => 'Las Naves', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-las-naves', 'parent_id' => 109, 'status_id' => 1],
            ['cat_name' => 'San Miguel', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-san-miguel', 'parent_id' => 109, 'status_id' => 1],
            ['cat_name' => 'Alausi', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-alausi', 'parent_id' => 110, 'status_id' => 1],
            ['cat_name' => 'Chambo', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-chambo', 'parent_id' => 110, 'status_id' => 1],
            ['cat_name' => 'Chunchi', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-chunchi', 'parent_id' => 110, 'status_id' => 1],
            ['cat_name' => 'Colta', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-colta', 'parent_id' => 110, 'status_id' => 1],
            ['cat_name' => 'Cumanda', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-cumanda', 'parent_id' => 110, 'status_id' => 1],
            ['cat_name' => 'Guamote', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-guamote', 'parent_id' => 110, 'status_id' => 1],
            ['cat_name' => 'Guano', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-guano', 'parent_id' => 110, 'status_id' => 1],
            ['cat_name' => 'Pallatanga', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-pallatanga', 'parent_id' => 110, 'status_id' => 1],
            ['cat_name' => 'Penipe', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-penipe', 'parent_id' => 110, 'status_id' => 1],
            ['cat_name' => 'Riobamba', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-riobamba', 'parent_id' => 110, 'status_id' => 1],
            ['cat_name' => 'Azogues', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-azoguez', 'parent_id' => 111, 'status_id' => 1],
            ['cat_name' => 'Biblian', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-biblian', 'parent_id' => 111, 'status_id' => 1],
            ['cat_name' => 'Cañar', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-canar', 'parent_id' => 111, 'status_id' => 1],
            ['cat_name' => 'Deleg', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-deleg', 'parent_id' => 111, 'status_id' => 1],
            ['cat_name' => 'El Tambo', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-el-tambo', 'parent_id' => 111, 'status_id' => 1],
            ['cat_name' => 'La Troncal', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-la-troncal', 'parent_id' => 111, 'status_id' => 1],
            ['cat_name' => 'Suscal', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-suscal', 'parent_id' => 111, 'status_id' => 1],
            ['cat_name' => 'Chordeleg', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-chordeleg', 'parent_id' => 112, 'status_id' => 1],
            ['cat_name' => 'Cuenca', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-cuenca', 'parent_id' => 112, 'status_id' => 1],
            ['cat_name' => 'El Pan', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-el-pan', 'parent_id' => 112, 'status_id' => 1],
            ['cat_name' => 'Giron', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-giron', 'parent_id' => 112, 'status_id' => 1],
            ['cat_name' => 'Guachapala', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-guachapala', 'parent_id' => 112, 'status_id' => 1],
            ['cat_name' => 'Gualaceo', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-gualaceo', 'parent_id' => 112, 'status_id' => 1],
            ['cat_name' => 'Nabon', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-nabon', 'parent_id' => 112, 'status_id' => 1],
            ['cat_name' => 'Oña', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-ona', 'parent_id' => 112, 'status_id' => 1],
            ['cat_name' => 'Paute', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-paute', 'parent_id' => 112, 'status_id' => 1],
            ['cat_name' => 'Ponce Enriquez', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-ponce-enriquez', 'parent_id' => 112, 'status_id' => 1],
            ['cat_name' => 'Pucara', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-pucara', 'parent_id' => 112, 'status_id' => 1],
            ['cat_name' => 'San Fernando', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-san-fernando', 'parent_id' => 112, 'status_id' => 1],
            ['cat_name' => 'Santa Isabel', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-santa-isabel', 'parent_id' => 112, 'status_id' => 1],
            ['cat_name' => 'Sevilla de Oro', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-sevilla-oro', 'parent_id' => 112, 'status_id' => 1],
            ['cat_name' => 'Sigsig', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-sigsig', 'parent_id' => 112, 'status_id' => 1],
            ['cat_name' => 'Calvas', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-calvas', 'parent_id' => 113, 'status_id' => 1],
            ['cat_name' => 'Catamayo', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-catamayo', 'parent_id' => 113, 'status_id' => 1],
            ['cat_name' => 'Celica', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-celica', 'parent_id' => 113, 'status_id' => 1],
            ['cat_name' => 'Chaguarpamba', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-chaguarpamba', 'parent_id' => 113, 'status_id' => 1],
            ['cat_name' => 'Espindola', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-espindola', 'parent_id' => 113, 'status_id' => 1],
            ['cat_name' => 'Gonzanama', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-gonzanama', 'parent_id' => 113, 'status_id' => 1],
            ['cat_name' => 'Loja', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-loja', 'parent_id' => 113, 'status_id' => 1],
            ['cat_name' => 'Macara', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-macara', 'parent_id' => 113, 'status_id' => 1],
            ['cat_name' => 'Olmedo', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-olmedo-loja', 'parent_id' => 113, 'status_id' => 1],
            ['cat_name' => 'Paltas', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-paltas', 'parent_id' => 113, 'status_id' => 1],
            ['cat_name' => 'Pindal', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-pindal', 'parent_id' => 113, 'status_id' => 1],
            ['cat_name' => 'Puyango', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-puyango', 'parent_id' => 113, 'status_id' => 1],
            ['cat_name' => 'Quilanga', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-quilanga', 'parent_id' => 113, 'status_id' => 1],
            ['cat_name' => 'Saraguro', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-saraguro', 'parent_id' => 113, 'status_id' => 1],
            ['cat_name' => 'Sozoranga', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-sozoranga', 'parent_id' => 113, 'status_id' => 1],
            ['cat_name' => 'Zapotillo', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-zapotillo', 'parent_id' => 113, 'status_id' => 1],
            ['cat_name' => 'Cascales', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-cascales', 'parent_id' => 114, 'status_id' => 1],
            ['cat_name' => 'Cuyabeno', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-cuyabeno', 'parent_id' => 114, 'status_id' => 1],
            ['cat_name' => 'Gonzalo Pizarro', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-gonzalo-pizarro', 'parent_id' => 114, 'status_id' => 1],
            ['cat_name' => 'Lago Agrio', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-lago-agrio', 'parent_id' => 114, 'status_id' => 1],
            ['cat_name' => 'Putumayo', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-putumayo', 'parent_id' => 114, 'status_id' => 1],
            ['cat_name' => 'Shushufindi', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-shushufindi', 'parent_id' => 114, 'status_id' => 1],
            ['cat_name' => 'Sucumbios', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-sucumbios', 'parent_id' => 114, 'status_id' => 1],
            ['cat_name' => 'Archidona', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-archidona', 'parent_id' => 115, 'status_id' => 1],
            ['cat_name' => 'Carlos Julio Arosemena Tola', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-carlos-julio-arosemena-tola', 'parent_id' => 115, 'status_id' => 1],
            ['cat_name' => 'El Chaco', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-el-chaco', 'parent_id' => 115, 'status_id' => 1],
            ['cat_name' => 'Quijos', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-quijos', 'parent_id' => 115, 'status_id' => 1],
            ['cat_name' => 'Tena', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-tena', 'parent_id' => 115, 'status_id' => 1],
            ['cat_name' => 'Aguarico', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-aguarico', 'parent_id' => 116, 'status_id' => 1],
            ['cat_name' => 'Orellana', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-orellana', 'parent_id' => 116, 'status_id' => 1],
            ['cat_name' => 'La Joya de los Sachas', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-la-joya-sachas', 'parent_id' => 116, 'status_id' => 1],
            ['cat_name' => 'Loreto', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-loreto', 'parent_id' => 116, 'status_id' => 1],
            ['cat_name' => 'Arajuno', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-arajuno', 'parent_id' => 117, 'status_id' => 1],
            ['cat_name' => 'Mera', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-mera', 'parent_id' => 117, 'status_id' => 1],
            ['cat_name' => 'Pastaza', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-pastaza', 'parent_id' => 117, 'status_id' => 1],
            ['cat_name' => 'Santa Clara', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-santa-clara', 'parent_id' => 117, 'status_id' => 1],
            ['cat_name' => 'Gualaquiza', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-gualaquiza', 'parent_id' => 118, 'status_id' => 1],
            ['cat_name' => 'Huamboya', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-huamboya', 'parent_id' => 118, 'status_id' => 1],
            ['cat_name' => 'Limon Indanza', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-limon-indanza', 'parent_id' => 118, 'status_id' => 1],
            ['cat_name' => 'Logroño', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-logrono', 'parent_id' => 118, 'status_id' => 1],
            ['cat_name' => 'Morona', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-morona', 'parent_id' => 118, 'status_id' => 1],
            ['cat_name' => 'Pablo Sexto', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-pablo-sexto', 'parent_id' => 118, 'status_id' => 1],
            ['cat_name' => 'Palora', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-palora', 'parent_id' => 118, 'status_id' => 1],
            ['cat_name' => 'San Juan Bosco', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-san-juan-bosco', 'parent_id' => 118, 'status_id' => 1],
            ['cat_name' => 'Santiago', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-santiago', 'parent_id' => 118, 'status_id' => 1],
            ['cat_name' => 'Sucua', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-sucua', 'parent_id' => 118, 'status_id' => 1],
            ['cat_name' => 'Taisha', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-taisha', 'parent_id' => 118, 'status_id' => 1],
            ['cat_name' => 'Tiwintza', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-tiwintza', 'parent_id' => 118, 'status_id' => 1],
            ['cat_name' => 'Centinela del Condor', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-centinela-condor', 'parent_id' => 119, 'status_id' => 1],
            ['cat_name' => 'Chinchipe', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-chinchipe', 'parent_id' => 119, 'status_id' => 1],
            ['cat_name' => 'El Pangui', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-el-pangui', 'parent_id' => 119, 'status_id' => 1],
            ['cat_name' => 'Nangaritza', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-nangaritza', 'parent_id' => 119, 'status_id' => 1],
            ['cat_name' => 'Palanda', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-palanda', 'parent_id' => 119, 'status_id' => 1],
            ['cat_name' => 'Paquisha', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-paquisha', 'parent_id' => 119, 'status_id' => 1],
            ['cat_name' => 'Yacuambi', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-yacuambi', 'parent_id' => 119, 'status_id' => 1],
            ['cat_name' => 'Yantzaza', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-yantzaza', 'parent_id' => 119, 'status_id' => 1],
            ['cat_name' => 'Zamora', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-zamora', 'parent_id' => 119, 'status_id' => 1],
            ['cat_name' => 'Isabela', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-isabela', 'parent_id' => 120, 'status_id' => 1],
            ['cat_name' => 'San Cristobal', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-san-cristobal', 'parent_id' => 120, 'status_id' => 1],
            ['cat_name' => 'Santa Cruz', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'canton-ec-santa-cruz', 'parent_id' => 120, 'status_id' => 1],

            /* Niveles Educativos */
            ['cat_name' => 'Niveles Educativos', 'cat_description' => NULL, 'cat_acronym' => 'NE', 'cat_keyword' => 'niveles-educativos', 'parent_id' => NULL, 'status_id' => 1],
            ['cat_name' => 'Ninguno', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'nivel-educativo-ninguno', 'parent_id' => 341, 'status_id' => 1],
            ['cat_name' => 'Centro alfabetizacion', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'nivel-educativo-centro-alfabetizacion', 'parent_id' => 341, 'status_id' => 1],
            ['cat_name' => 'Jardin infantes', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'nivel-educativo-jardin-infantes', 'parent_id' => 341, 'status_id' => 1],
            ['cat_name' => 'Educacion basica', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'nivel-educativo-edu-basica', 'parent_id' => 341, 'status_id' => 1],
            ['cat_name' => 'Educacion media', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'nivel-educativo-edu-media', 'parent_id' => 341, 'status_id' => 1],
            ['cat_name' => 'Superior no universitaria completa', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'nivel-educativo-edu-no-superior-completa', 'parent_id' => 341, 'status_id' => 1],
            ['cat_name' => 'Superior no universitaria incompleta', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'nivel-educativo-edu-no-superior-incompleta', 'parent_id' => 341, 'status_id' => 1],
            ['cat_name' => 'Superior universitaria completa', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'nivel-educativo-edu-superior-completa', 'parent_id' => 341, 'status_id' => 1],
            ['cat_name' => 'Superior universitaria incompleta', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'nivel-educativo-edu-superior-incompleta', 'parent_id' => 341, 'status_id' => 1],
            ['cat_name' => 'Posgrado maestria', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'nivel-educativo-postgrado-maestria', 'parent_id' => 341, 'status_id' => 1],
            ['cat_name' => 'Posgrado PHD', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'nivel-educativo-postgrado-phd', 'parent_id' => 341, 'status_id' => 1],
            ['cat_name' => 'Diplomado', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'nivel-educativo-diplomado', 'parent_id' => 341, 'status_id' => 1],
            ['cat_name' => 'Especialidad', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'nivel-educativo-especialidad', 'parent_id' => 341, 'status_id' => 1],
            ['cat_name' => 'No registra', 'cat_description' => NULL, 'cat_acronym' => NULL, 'cat_keyword' => 'nivel-educativo-no-registra', 'parent_id' => 341, 'status_id' => 1],
        ]);
    }
}
